=== bbc/bbcrd-ips-grouping/specification/schemas/groupingapi-v2.0-package-patch.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "Patch update a resource. Include the fields to be patched. null is used to remove a field. Only some fields can be removed",
    "title": "Package PATCH",
    "properties": {
      "id": {
        "description": "Globally unique identifier for the Package",
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "group_id": {
        "description": "Globally unique identifier for packaged Group",
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "label": {
        "description": "Freeform string label for the Package",
        "type": "string"
      },
      "description": {
        "description": "Freeform string description for the Package",
        "type": "string"
      },
      "min_ts": {
        "description": "TAI timestamp formatted as <s>:<ns>",
        "type": "string",
        "pattern": "^\\d+:\\d+"
      },
      "max_ts": {
        "anyOf":[
          {
            "description": "TAI timestamp formatted as <s>:<ns>",
            "type": "string",
            "pattern": "^\\d+:\\d+"
          },
          {
            "type": null
          }
        ]
      },
      "tags": {"$ref": "groupingapi-v2.0-tag.json"}
    },
    "additionalProperties": false
  }

=== bbc/bbcrd-ips-grouping/specification/examples/groupingapi-v2.0-packages-get-200.json
[{
    "id": "c51b2f8c-c30a-4546-a4a3-d0a8257484f1",
    "group_id": "c51b2f8c-c30a-4546-a4a3-d0a8257484f2",
    "tags": {"network": ["bbc_one"]},
    "min_ts": "1487334138:1233",
    "max_ts": "1487335000:25987373",
    "label": "Sherlock Series 4 Episode 2",
    "description": "Example description of package"
},
{
    "id": "c51b2f8c-c30a-4546-a4a3-d0a8257484f3",
    "group_id": "c51b2f8c-c30a-4546-a4a3-d0a8257484f4",
    "tags": {"network": ["bbc_one"]},
    "min_ts": "1487334138:1233",
    "max_ts": "1487335000:25987373",
    "label": "Camera A Fixed - Take 2",
    "description": "Example description of package"
}
]
