=== bbc/bbcrd-ips-grouping/specification/schemas/groupingapi-v2.0-group-patch.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "description": "Patch update a resource. Include the fields to be patched. null is used to remove a field. Only some fields can be removed",
    "title": "Group PATCH",
    "properties": {
      "id": {
        "description": "Globally unique identifier for the Group",
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "label": {
        "description": "Freeform string label for the Group",
        "type": "string"
      },
      "description": {
        "description": "Freeform string description for the Group",
        "type": "string"
      },
      "resource_type": {
        "description": "Type of the resources refered to in members",
        "type": "string"
      },
      "members": {
        "description": "Hash of UUIDs representing the IDs of resources to be grouped together by this group. null is used to remove a key",
        "type": "object",
        "patternProperties": {
          "^.*$": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
              },
              {
                "type": null
              }
            ]
          }
        },
        "additionalProperties": false
      },
      "tags": {"$ref": "groupingapi-v2.0-tag.json"}
    },
    "additionalProperties": false
  }

=== bbc/bbcrd-ips-grouping/specification/examples/groupingapi-v2.0-groups-get-200.json
[{
    "id": "c51b2f8c-c30a-4546-a4a3-d0a8257484f9",
    "label": "Example DASH Adaptation Set",
    "description": "Example description of DASH Adaptation Set",
    "resource_type": "flow",
    "tags": {"domain": ["BBCNews"]},
    "members": {
        "video": "c51b2f8c-c30a-4546-a4a3-d0a8257484f8",
        "audio": "c51b2f8c-c30a-4546-a4a3-d0a8257484f7",
        "subs": "c51b2f8c-c30a-4546-a4a3-d0a8257484f6",
        "dialog_eng": "c51b2f8c-c30a-4546-a4a3-d0a8257484f5"
    }
},
{
    "id": "c51b2f8c-c30a-4546-a4a3-d0a8257484f4",
    "label": "Camera A Fixed",
    "description": "Example description",
    "resource_type": "source",
    "tags": {"domain": ["BBCNews"]},
    "members": {
        "video_raw": "c51b2f8c-c30a-4546-a4a3-d0a8257484f3",
        "video_mezzanine": "c51b2f8c-c30a-4546-a4a3-d0a8257484f2",
        "audio": "c51b2f8c-c30a-4546-a4a3-d0a8257484f1"
    }
}
]

=== bbc/bbcrd-ips-grouping/specification/examples/groupingapi-v2.0-group-get-200.json
{
    "id": "2dc2f736-db06-11e5-b5d2-0a1d41d68578",
    "label": "Example DASH Adaptation Set",
    "description": "Example description of DASH Adaptation Set",
    "resource_type": "flow",
    "tags": {"domain": ["BBCNews"]},
    "members": {
        "video": "2dc2f736-db06-11e5-b5d2-0a1d41d68578",
        "audio": "4dc2f736-db06-11e5-b5d2-0a1d41d68543",
        "subs": "2dc2f736-db06-11e5-b5d2-0a1d41d68599",
        "dialog_eng": "1dc2f736-db06-11e5-b5d2-0a1d41d68578"
    }
}
